### ISSUE TITLE
About the MATLAB script

### ISSUE THREAD

**Issue by Orthocenter** [seemoo-lab/mobisys2018_nexmon_channel_state_information_extractor#1]
Great work! I have already used this extractor to capture CSI on a Nexus 5. However, for now I am not able to parse the captured CSI data. So I just want to ask when will the MATLAB script for analyzing be published? Thanks.

**Comment by matthiasseemoo** [comment]
You can now find an example matlab script to extract and interpret the dumped CSI in the `matlab` directory.

**Comment by Orthocenter** [comment]
thanks!
