### ISSUE TITLE
64d0

### ISSUE THREAD

**Issue by zxy110** [seemoo-lab/mobisys2018_nexmon_channel_state_information_extractor#10]
Hi,
   I'm confused the setting of argument,  could you tell me why `channel 100 with a bandwidth of 20 MHz` is represented by `64d0`?
   Thanks very much.

Jenny Doe

**Comment by matthiasseemoo** [comment]
It is the chanspec represented as a hexnumber, see
https://github.com/seemoo-lab/nexmon/blob/master/patches/include/channels.h
and keep the endianess in mind.

Jenny Doe <notifications@github.com> schrieb am Di., 17. Juli 2018, 08:11:

**Comment by zxy110** [comment]
Thanks very much. 

But I still confused about the setting of bandwidth .  I don't know what's the connection of 20MHz with d0 .  Do you know how it works ?  Thanks a lot .

**Comment by matthiasseemoo** [comment]
0xc0 = 5 GHz
0x10 = 20 MHz BW
0xc0 or 0x10 = 0xd0

Jenny Doe <notifications@github.com> schrieb am Fr., 27. Juli 2018, 10:35:

**Comment by Twighterr** [comment]
According to channels.c, 
5GHz = 0xc000
20MHz = 0x1000
0xc000 or 0x1000 = 0xd000
Why is it 64d0 instead of d064?
