### ISSUE TITLE
Compile error when run make

### ISSUE THREAD

**Issue by tangbao** [seemoo-lab/mobisys2018_nexmon_channel_state_information_extractor#16]
Hi, I meet some problems when compiling nexmon, and I think it is because the bison.

.I am using a Xubuntu 16.04 LTS on a virtual machine powered by Virtual Box.

I strictly followed the guideline in README. In step 7 of "Getting Started", when I ran make, it first had an error "/bin/sh: 1: bison: not found" so I installed the bison and bison:i386, then re-ran the make and the following error occured:

tangbao@tangbao-VirtualBox:~/nexmon$ make
  BUILDING BUILDTOOLS
make[1]: Entering directory '/home/tangbao/nexmon/buildtools'
  BUILDING flash_patch_extractor
make[2]: Entering directory '/home/tangbao/nexmon/buildtools/flash_patch_extractor'
gcc -std=c99 -Wall -Wno-unused-result -O0 -D_BSD_SOURCE -o fpext.o -c fpext.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/armv7.o -c darm/armv7.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/armv7-tbl.o -c darm/armv7-tbl.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/darm.o -c darm/darm.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/darm-tbl.o -c darm/darm-tbl.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/thumb2.o -c darm/thumb2.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/thumb2-decoder.o -c darm/thumb2-decoder.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/thumb2-tbl.o -c darm/thumb2-tbl.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/thumb.o -c darm/thumb.c
gcc -std=c99 -Wall -O2 -Wextra -Wno-missing-field-initializers -o darm/thumb-tbl.o -c darm/thumb-tbl.c
gcc -o fpext fpext.o darm/armv7.o darm/armv7-tbl.o darm/darm.o darm/darm-tbl.o darm/thumb2.o darm/thumb2-decoder.o darm/thumb2-tbl.o darm/thumb.o darm/thumb-tbl.o
make[2]: Leaving directory '/home/tangbao/nexmon/buildtools/flash_patch_extractor'
  BUILDING ucode_extractor
make[2]: Entering directory '/home/tangbao/nexmon/buildtools/ucode_extractor'
gcc -std=c99 -Wall -Wno-unused-result -O0 -D_BSD_SOURCE -o ucodeext.o -c ucodeext.c
gcc -o ucodeext ucodeext.o
make[2]: Leaving directory '/home/tangbao/nexmon/buildtools/ucode_extractor'
  BUILDING b43/assembler/b43-asm.bin
make[2]: Entering directory '/home/tangbao/nexmon/buildtools/b43/assembler'
     DEPEND   dep/util.d
     YACC     parser.c
     LEX      scanner.c
/bin/sh: 1: flex: not found
     DEPEND   dep/parser.d
     DEPEND   dep/main.d
     DEPEND   dep/initvals.d
     DEPEND   dep/args.d
     LEX      scanner.c
/bin/sh: 1: flex: not found
     CC       obj/args.o
     CC       obj/initvals.o
     CC       obj/main.o
     CC       obj/parser.o
parser.c: In function ‘yyparse’:
parser.c:4330:18: warning: passing argument 1 of ‘yyerror’ discards ‘const’ qualifier from pointer target type [-Wdiscarded-qualifiers]
         yyerror (yymsgp);
                  ^
parser.y:26:13: note: expected ‘char *’ but argument is of type ‘const char *’
 extern void yyerror(char *);
             ^
     CC       obj/scanner.o
gcc: fatal error: no input files
compilation terminated.
Makefile:52: recipe for target 'obj/scanner.o' failed
make[2]: *** [obj/scanner.o] Error 1
make[2]: Leaving directory '/home/tangbao/nexmon/buildtools/b43/assembler'
Makefile:4: recipe for target 'b43/assembler/b43-asm.bin' failed
make[1]: *** [b43/assembler/b43-asm.bin] Error 2
make[1]: Leaving directory '/home/tangbao/nexmon/buildtools'
Makefile:8: recipe for target 'buildtools' failed
make: *** [buildtools] Error 2

Hope to get some help. Thank you.

**Comment by matthiasseemoo** [comment]
Did you install flex?

Am Mo., 10. Dez. 2018, 06:19 hat Zhongze Tang <notifications@github.com>
geschrieben:

**Comment by tangbao** [comment]
@matthiasseemoo  Sorry, no, because I don't know what are bison and flex actually... 

No error occurs again after I install flex. Seems that everything is OK now.

Thank you very much.
