### ISSUE TITLE
Router Requirements

### ISSUE THREAD

**Issue by maxbeech** [seemoo-lab/mobisys2018_nexmon_channel_state_information_extractor#21]
The installation process on the Nexus 5 has been very well documented here, but what are the WiFi router requirements please?

The only reference I can see to what routers are required is this: 
> OFDM-modulated Wi-Fi frames (802.11a/(g)/n/ac)

But sadly I don't understand what that means. 

Alternative CSI collection tools like [this one](https://github.com/xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src/wiki/Getting-started-with-Atheros-CSI-tool) explain compatibility is limited to routers with a specific wireless chip.

Many thanks!

PS. I currently have a TP-Link Archer C1200 v4

**Comment by matthiasseemoo** [comment]
I just used an apple timecapsule  however you can use any other wifi device
to inject frames. I just wanted to simplify the setup by listening for
beacon frames.

Max Beech <notifications@github.com> schrieb am So., 17. März 2019, 16:37:

**Comment by maxbeech** [comment]
Hey @matthiasseemoo - many thanks for your reply.

Ok gotcha, so trying to get my head around this. Does Nexmon's approach of accessing CSI via router beacon frames simpler mean they don't need to modify the router to send out the raw signal (which I think is how other solutions like the [Atheros one](https://github.com/xieyaxiongfly/Atheros_CSI_tool_OpenWRT_src/wiki/Getting-started-with-Atheros-CSI-tool) works? 

And if so, are there any disadvantages to using beacon frames? Do they send out as much CSI information as the Atheros approach please?

Thanks so much!
Max

**Comment by matthiasseemoo** [comment]
In the end, they are never amsdus, which we currently cannot handle using
our approach. Unfortunately, I the beacons are normally send on 20 MHz
control channels. If you want to cover larger bandwidths, you need to
inject your own frames and disable the generation of amsdus.

Max Beech <notifications@github.com> schrieb am So., 17. März 2019, 21:17:

**Comment by maxbeech** [comment]
Many thanks for the info @matthiasseemoo, much appreciated.
